# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonnaci_sum(b):
    f_1 = 1
    f_2 = 1
    sum_even = 0
    while f_2 < b:
        f_2, f_1 = f_2 + f_1, f_2
        if not f_2 % 2:
            sum_even += f_2
    return sum_even


if __name__ == "__main__":
    bound = 4 * 10**6
    print(fibonnaci_sum(bound))
